### ISSUE TITLE
Impossible de télécharger ce film.. problème d'encodage?

### ISSUE THREAD

**Issue by thenamelessthing** [CouchPotato/CouchPotatoServer#6073]
### Steps to reproduce:
1. .. Il veut pas fonctionner ce téléchargement.... pourquoi??
2. ..

### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 89fd4e11 (2016-01-24 04:42:44)
Running on: ...

### Logs:
```
02-11 20:40:32 ERROR [o.core.downloaders.deluge] Failed to add torrent file Le Dernier Maitre de lAir 1920x816.mp4 french.torrent: not a valid bencoded string Traceback (most recent call last):
  File "/opt/couchpotato/couchpotato/core/downloaders/deluge.py", line 258, in add_torrent_file
    torrent_id = self._check_torrent(False, torrent)
  File "/opt/couchpotato/couchpotato/core/downloaders/deluge.py", line 322, in _check_torrent
    info = bdecode(torrent)["info"]
  File "/opt/couchpotato/libs/bencode/__init__.py", line 68, in bdecode
    raise BTFailure("not a valid bencoded string")
BTFailure: not a valid bencoded string
 
```

**Comment by eddydg** [comment]
Il semblerait que ce soit un problème déjà signalé : https://github.com/CouchPotato/CouchPotatoServer/issues/5492
