### ISSUE TITLE
UnicodeEncodeError on updating RSS feed for iTunes

### ISSUE THREAD

**Issue by neothematrix** [CouchPotato/CouchPotatoServer#6109]
hi,
I'm currently using this URL to get automatic download of top movies from the iTunes italian catalog: https://itunes.apple.com/it/rss/topmovies/limit=25/xml
I started getting this error:

```
02-21 10:01:07 INFO [hpotato.core.plugins.base] Opening url: get https://itunes.apple.com/it/rss/topmovies/limit=25/xml, data: []
02-21 10:01:08 INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/search/Spectre+2015/?limit=1, data: []
02-21 10:01:08 INFO [hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/search/movie?api_key=xxx&search_type=phrase&query=spectre&year=2015, data: []
02-21 10:01:08 INFO [hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&y=2015&t=spectre, data: []
02-21 10:01:08 INFO [ie.providers.info.omdbapi] Found: Spectre (2015)
02-21 10:01:08 INFO [hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/search/movie?api_key=xxx&search_type=phrase&query=lo+stagista+inaspettato&year=2015, data: []
02-21 10:01:08 INFO [hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&y=2015&t=lo+stagista+inaspettato, data: []
02-21 10:01:08 INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/search/Lo+stagista+inaspettato+2015/?limit=1, data: []
02-21 10:01:08 INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/search/Se+Dio+vuole+2015/?limit=1, data: []
02-21 10:01:08 INFO [hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&y=2015&t=dio+vuole, data: []
02-21 10:01:08 INFO [ie.providers.info.omdbapi] Found: Se Dio vuole (2015)
02-21 10:01:09 INFO [hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/search/movie?api_key=xxx&search_type=phrase&query=dio+vuole&year=2015, data: []
02-21 10:01:09 INFO [providers.automation.base] rating too low for Se Dio vuole, need 7.0 has 6.6
02-21 10:01:09 INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/search/Suburra+2015/?limit=1, data: []
02-21 10:01:09 INFO [hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&y=2015&t=suburra, data: []
02-21 10:01:09 INFO [ie.providers.info.omdbapi] Found: Suburra (2015)
02-21 10:01:09 INFO [hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/search/movie?api_key=xxx&search_type=phrase&query=suburra&year=2015, data: []
02-21 10:01:09 INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/search/The+Martian+-+Sopravvissuto+2015/?limit=1, data: []
02-21 10:01:09 INFO [hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&y=2015&t=the+martian+sopravvissuto, data: []
02-21 10:01:09 INFO [hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/search/movie?api_key=xxx&search_type=phrase&query=the+martian+sopravvissuto&year=2015, data: []
02-21 10:01:09 INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/search/Hitman%3A+Agente+47+%28Hitman%3A+Agent+47%29+2015/?limit=1, data: []
02-21 10:01:09 INFO [hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&y=2015&t=hitman+agente+47+hitman+agent+47, data: []
02-21 10:01:10 INFO [hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/search/movie?api_key=xxx&search_type=phrase&query=hitman+agente+47+hitman+agent+47&year=2015, data: []
02-21 10:01:10 INFO [providers.automation.base] rating too low for Hitman: Agent 47, need 7.0 has 5.8
02-21 10:01:10 INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/search/Inside+Out+%282015%29+2015/?limit=1, data: []
02-21 10:01:10 INFO [hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&y=2015&t=inside+out+2015, data: []
02-21 10:01:10 INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/search/Hotel+Transylvania+2+2015/?limit=1, data: []
02-21 10:01:10 INFO [hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&y=2015&t=hotel+transylvania+2, data: []
02-21 10:01:10 INFO [ie.providers.info.omdbapi] Found: Hotel Transylvania 2 (2015)
02-21 10:01:10 INFO [providers.automation.base] rating too low for Hotel Transylvania 2, need 7.0 has 6.8
02-21 10:01:10 INFO [hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&y=2015&t=maze+runner+la+fuga, data: []
02-21 10:01:10 INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/search/Maze+Runner%3A+La+Fuga+2015/?limit=1, data: []
02-21 10:01:10 INFO [providers.automation.base] rating too low for Maze Runner: The Scorch Trials, need 7.0 has 6.4
02-21 10:01:10 ERROR [oviders.automation.itunes] Failed loading iTunes rss feed: https://itunes.apple.com/it/rss/topmovies/limit=25/xml Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/CouchPotato2/CouchPotato2/couchpotato/core/media/movie/providers/automation/itunes.py", line 56, in getIMDBids
    imdb = self.search(name, year)
  File "/share/CACHEDEV1_DATA/.qpkg/CouchPotato2/CouchPotato2/couchpotato/core/media/movie/providers/automation/base.py", line 49, in search
    cached_imdb = Env.prop(prop_name, default = False)
  File "/share/CACHEDEV1_DATA/.qpkg/CouchPotato2/CouchPotato2/couchpotato/environment.py", line 82, in prop
    v = s.getProperty(identifier)
  File "/share/CACHEDEV1_DATA/.qpkg/CouchPotato2/CouchPotato2/couchpotato/core/settings.py", line 420, in getProperty
    propert = db.get('property', identifier)
  File "/share/CACHEDEV1_DATA/.qpkg/CouchPotato2/CouchPotato2/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner
    res = f(*args, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/CouchPotato2/CouchPotato2/libs/CodernityDB/database.py", line 940, in get
    l_key, _unk, start, size, status = ind.get(key)
  File "/share/CACHEDEV1_DATA/.qpkg/CouchPotato2/CouchPotato2/libs/CodernityDB/hash_index.py", line 382, in get
    return self._find_key(self.make_key(key))
  File "<Index: /share/CACHEDEV1_DATA/.qpkg/CouchPotato2/config/database/_indexes/03property.py", line 33, in make_key
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf2' in position 26: ordinal not in range(128)
```

it must have something to do with one of the currently present movie titles that has accents: `Tutto può accadere a Broadway - Peter Bogdanovich` because I can see in the logs that it stops exactly after parsing the previous movie.

this is a pastebin "snapshot" of the current xml page in case it changes: http://pastebin.com/GEc40H08

I'm using the qnap package of CouchPotato, which is updated to the latest "master" branch.

**Comment by neothematrix** [comment]
I temporarily fixed it with this workaround, not sure if it's the right way, but it seems to work:

```
diff --git a/couchpotato/core/media/movie/providers/automation/itunes.py b/couchpotato/core/media/movie/providers/automation/itunes.py
index 63655f9..057727d 100644
--- a/couchpotato/core/media/movie/providers/automation/itunes.py
+++ b/couchpotato/core/media/movie/providers/automation/itunes.py
@@ -47,7 +47,7 @@ class ITunes(Automation, RSS):

                     for movie in rss_movies:
                         name_tag = str(QName(namespace_im, 'name'))
-                        name = self.getTextElement(movie, name_tag)
+                        name = self.getTextElement(movie, name_tag).encode('utf-8')

                         releaseDate_tag = str(QName(namespace_im, 'releaseDate'))
                         releaseDateText = self.getTextElement(movie, releaseDate_tag)
```

**Comment by neothematrix** [comment]
the issue is still present, any change to fix this?
