### ISSUE TITLE
Fresh install of CouchPotato met with white page

### ISSUE THREAD

**Issue by phyxius90** [CouchPotato/CouchPotatoServer#6262]
### Steps to reproduce:
I have just installed CouchPotato on a fresh windows 10. It is "connecting" to the localhost and the computer, but it only shows a white page.

What can I do to fix this? I have tried several versions, removed adblock. My browser is firefox.
I have tried with Opera, there I get this: 
`This site can’t be reached

localhost refused to connect.
Check your internet connection.

Check any cables and reboot any routers, modems, or other network devices you may be using.
If it is already listed as a program allowed to access the network, try removing it from the list and adding it again.
If you use a proxy server...

Check your proxy settings or contact your network administrator to make sure the proxy server is working. If you don't believe you should be using a proxy server:`
### Information:

Providers I use: 
Version of CouchPotato: 3.0.1 amd64, have tried others aswell
Running on: win10 edu

This is what I get when I quit CouchPotato
### Logs:
`Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 764: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 765: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 761: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 767: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 764: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 765: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 761: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 767: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 767: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 765: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 761: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 764: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 767: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 761: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 764: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 765: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 761: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 761: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 767: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 742: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 767: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 742: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 812: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 813: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 809: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 809: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 815: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 815: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 812: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 813: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 809: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 815: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 812: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 809: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 813: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 815: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 809: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 815: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 812: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 813: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 809: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 815: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 809: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 815: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 812: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 815: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 813: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 809: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 809: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 815: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 812: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 813: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 809: ordinal not in range(128)
Logged from file web.py, line 1421
Traceback (most recent call last):
  File "logging\__init__.pyc", line 882, in emit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 815: ordinal not in range(128)
Logged from file web.py, line 1421
`

**Comment by phyxius90** [comment]
Solved, norwegian letter in my name fucked it up, just changed the folder :-)
